# Generated by Django 2.2.6 on 2019-11-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Board', '0001_initial'),
        ('PlayerInfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('turn_number', models.IntegerField(default=0)),
                ('robber_moved', models.BooleanField(default=False)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Board.Board')),
                ('deck', models.ManyToManyField(to='Board.Card')),
                ('dices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='Games.Dice')),
                ('in_turn', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_turn', to='PlayerInfo.Player')),
                ('largest_army', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='largest_army', to='PlayerInfo.Player')),
                ('longest_path', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longest_path', to='PlayerInfo.Player')),
                ('players', models.ManyToManyField(related_name='players', to='PlayerInfo.Player')),
                ('robber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Board.VertexPosition')),
                ('winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='PlayerInfo.Player')),
            ],
        ),
    ]
