# Generated by Django 2.2.6 on 2019-11-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=30)),
                ('development_cards', models.IntegerField(default=0)),
                ('resources_cards', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(related_name='cards', to='Board.Card')),
                ('cities', models.ManyToManyField(related_name='cities', to='Board.VertexPosition')),
                ('last_gained', models.ManyToManyField(related_name='last_gained', to='Board.Resource')),
                ('resources', models.ManyToManyField(related_name='res', to='Board.Resource')),
                ('roads', models.ManyToManyField(related_name='roads', to='Board.RoadPosition')),
                ('settlements', models.ManyToManyField(related_name='settlements', to='Board.VertexPosition')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
